# Custom Language File for Launcher Customizer

[ejs.app]
title = "다이아 룰렛"

[ejs.landing]
mediaGitHubURL = "https://github.com/mchlauncher/DiaRoulette"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = ""
mediaSoopURL = "#"
mediaChzzkURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/mchlauncher/DiaRoulette"
supportLink = "https://github.com/mchlauncher/DiaRoulette/issues"

[ejs.welcome]
welcomeHeader = "다이아 룰렛"
welcomeDescription = ""
welcomeDescCTA = "[계속] 버튼을 눌러 계속 진행하여 주세요."